from celery import shared_task
from django.core.mail import send_mail

@shared_task
def notify_admin_new_post(title, content, username,userid):
    send_mail(
        subject=f"New AI Post Generated by {userid}",
        message=f"USERNAME: {username}Title: {title}\n\nContent:\n{content[:500]}",
        from_email="jaswanth20000005@gmail.com",
        recipient_list=["jaswanthcyber@gmail.com"],
    )