# Generated by Django 5.2.11 on 2026-02-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('user_id', models.IntegerField()),
                ('blog', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
